// SPDX-License-Identifier: MIT
pragma solidity >=0.8.4;

/// @notice Interface for the UltraVerifier generated by the Barretenberg ZK Backend
interface IUltraVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

/// @title Veil Registry Smart Contract
/// @notice This contract accepts Zero-Knowledge proofs from the Veil mobile app
/// to verify user eligibility (e.g., balance, contributions) without revealing private data.
contract VeilRegistry {
    IUltraVerifier public verifier;
    
    // The public key of the trusted zkTLS Node (Reclaim Protocol / Govt API)
    // The ZK Proof ensures the user's private data was signed by this key
    bytes32 public trustedAttesterPubKeyX;
    bytes32 public trustedAttesterPubKeyY;

    // Minimum requirements set by the grant program
    uint256 public requiredMinBalance = 5000;
    uint256 public requiredMinPrs = 1;

    // Mapping to track which users have successfully claimed the grant to prevent double-spending
    mapping(address => bool) public hasClaimed;

    event GrantClaimed(address indexed beneficiary);

    constructor(address _verifierAddress, bytes32 _pubKeyX, bytes32 _pubKeyY) {
        verifier = IUltraVerifier(_verifierAddress);
        trustedAttesterPubKeyX = _pubKeyX;
        trustedAttesterPubKeyY = _pubKeyY;
    }

    /// @notice Submits a ZK Proof to claim the grant
    /// @param proof The zero-knowledge proof byte array generated by the Noir mobile prover
    function claimGrant(bytes calldata proof) external {
        require(!hasClaimed[msg.sender], "Grant already claimed");

        // The public inputs must exactly match the public parameters defined in the Noir circuit:
        // [min_balance, min_prs, attester_pub_key_x, attester_pub_key_y]
        bytes32[] memory publicInputs = new bytes32[](4);
        publicInputs[0] = bytes32(requiredMinBalance);
        publicInputs[1] = bytes32(requiredMinPrs);
        publicInputs[2] = trustedAttesterPubKeyX;
        publicInputs[3] = trustedAttesterPubKeyY;

        // Verify the ZK Proof using the generated UltraVerifier contract
        // If this passes, it mathematically proves:
        // 1. The user's private data was signed by the trustedAttester (Data Provenance)
        // 2. The user's balance >= requiredMinBalance
        // 3. The user's PRs >= requiredMinPrs
        bool isProofValid = verifier.verify(proof, publicInputs);
        require(isProofValid, "Invalid Zero-Knowledge Proof");

        // Mark as claimed
        hasClaimed[msg.sender] = true;

        // In a real implementation, transfer tokens or emit an event for an off-chain relayer
        emit GrantClaimed(msg.sender);
    }
}
