// SPDX-License-Identifier: MIT
pragma solidity >=0.8.4;

/// @notice Interface for the UltraVerifier generated by the Barretenberg ZK Backend
interface IUltraVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

/// @title Veil Registry Smart Contract
/// @notice This contract accepts Zero-Knowledge proofs from the Veil mobile app
/// to verify user eligibility (e.g., balance, contributions) without revealing private data.
contract VeilRegistry {
    IUltraVerifier public verifier;
    address public admin;

    struct Program {
        string name;
        uint256 requiredMinBalance;
        uint256 requiredMinPrs;
        bool isActive;
    }

    // programId => Program details
    mapping(uint256 => Program) public programs;
    uint256 public nextProgramId;

    // programId => user address => hasClaimed
    mapping(uint256 => mapping(address => bool)) public hasClaimed;

    event ProgramAdded(uint256 indexed programId, string name, uint256 minBalance, uint256 minPrs);
    event GrantClaimed(uint256 indexed programId, address indexed beneficiary);

    modifier onlyAdmin() {
        require(msg.sender == admin, "Not authorized");
        _;
    }

    constructor(address _verifierAddress) {
        verifier = IUltraVerifier(_verifierAddress);
        admin = msg.sender;
    }

    /// @notice Allows the admin to add a new grant program with specific requirements
    function addProgram(string memory name, uint256 minBalance, uint256 minPrs) external onlyAdmin {
        programs[nextProgramId] = Program({
            name: name,
            requiredMinBalance: minBalance,
            requiredMinPrs: minPrs,
            isActive: true
        });
        emit ProgramAdded(nextProgramId, name, minBalance, minPrs);
        nextProgramId++;
    }

    /// @notice Submits a ZK Proof to claim a specific grant program
    /// @param programId The ID of the program the user is applying for
    /// @param proof The zero-knowledge proof byte array generated by the Noir mobile prover
    function claimGrant(uint256 programId, bytes calldata proof) external {
        Program memory program = programs[programId];
        require(program.isActive, "Program is not active");
        require(!hasClaimed[programId][msg.sender], "Grant already claimed for this program");

        // The public inputs must exactly match the public parameters defined in the Noir circuit:
        // [min_balance, min_prs]
        bytes32[] memory publicInputs = new bytes32[](2);
        publicInputs[0] = bytes32(program.requiredMinBalance);
        publicInputs[1] = bytes32(program.requiredMinPrs);

        // Verify the ZK Proof using the generated UltraVerifier contract
        // If this passes, it mathematically proves:
        // 1. The user's balance >= program.requiredMinBalance
        // 2. The user's PRs >= program.requiredMinPrs
        bool isProofValid = verifier.verify(proof, publicInputs);
        require(isProofValid, "Invalid Zero-Knowledge Proof");

        // Mark as claimed
        hasClaimed[programId][msg.sender] = true;

        // In a real implementation, transfer tokens or emit an event for an off-chain relayer
        emit GrantClaimed(programId, msg.sender);
    }
}
