// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title SimulatedVerifier
 * @notice Accepts the deterministic HMAC-SHA256 proof format generated by Veil's
 *         Flutter ProofService. This is a stand-in for UltraVerifier.sol (Noir/Barretenberg).
 *         When real on-device Barretenberg proving is integrated, replace this contract
 *         with the auto-generated UltraVerifier.sol from `bb write_verifier`.
 *
 * @dev Proof format (1024 hex chars = 512 bytes):
 *      - Bytes [0..31]   : HMAC-SHA256 commitment hash (binds private witness to public statement)
 *      - Bytes [32..511] : Deterministic pseudorandom expansion seeded from commitment hash
 *
 *      Public inputs format (2 elements):
 *      - publicInputs[0] : SHA256("balance_threshold:<minBalance>") as uint256
 *      - publicInputs[1] : SHA256("prs_threshold:<minPrs>") as uint256
 */
contract SimulatedVerifier {
    /// @notice Minimum proof length: 512 bytes = 1024 hex characters.
    uint256 public constant PROOF_MIN_LENGTH = 1024;

    /**
     * @notice Verifies a simulated ZK proof.
     * @dev Checks:
     *   1. Proof is not empty and meets minimum length.
     *   2. Two public inputs are provided.
     *   3. First 32 bytes (commitment) are not the zero hash.
     *   In production, replace this body with a call to the Barretenberg UltraVerifier.
     *
     * @param proof        The hex-encoded proof bytes from ProofService.dart.
     * @param publicInputs Array of 2 uint256 values (hashed thresholds).
     * @return True if the proof is structurally valid and commitment is non-zero.
     */
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external pure returns (bool) {
        // Basic structural checks
        require(
            proof.length >= PROOF_MIN_LENGTH / 2,
            "SimulatedVerifier: proof too short"
        );
        require(
            publicInputs.length == 2,
            "SimulatedVerifier: need 2 public inputs"
        );
        require(
            publicInputs[0] != 0,
            "SimulatedVerifier: balance input is zero"
        );
        require(publicInputs[1] != 0, "SimulatedVerifier: prs input is zero");

        // Extract the first 32 bytes as the commitment word
        bytes32 commitment;
        assembly {
            commitment := calldataload(proof.offset)
        }

        // The commitment must be non-zero (a real HMAC-SHA256 output is never all-zero)
        require(commitment != bytes32(0), "SimulatedVerifier: zero commitment");

        return true;
    }
}
